### ISSUE TITLE
🍰

### ISSUE THREAD

**Issue by Malwine** [rubycorns/organization#1]
😰

**Comment by lislis** [comment]
the number 1 issue. I love it.

**Comment by berlintam** [comment]
bahahahaha. 

@Malwine where is our cake!?

**Comment by til** [comment]
also @Malwine promised to ...

can't wait for this issue to get closed!

**Comment by PragTob** [comment]
I don't see unicode stuff, but I assume it is about...

![cake](http://media1.giphy.com/media/aVbRuyBvabexy/giphy.gif)

**Comment by til** [comment]
cake for linux users:  
![cake](https://cloud.githubusercontent.com/assets/11211/8065135/c23499f4-0edf-11e5-9b4c-c3ac3aff540b.png)

sigh ;-)

**Comment by Malwine** [comment]
![bildschirmfoto 2015-06-09 um 19 49 01](https://cloud.githubusercontent.com/assets/5123681/8065248/9b0f41fc-0ee0-11e5-874f-9b25740dca10.jpg)

Schade.... :-0

**Comment by Malwine** [comment]
![cake](https://cloud.githubusercontent.com/assets/5123681/9068304/023e87ec-3ae3-11e5-9746-fe194c20cdfc.jpg)
