### ISSUE TITLE
Project Group BBQ

### ISSUE THREAD

**Issue by sareg0** [rubycorns/organization#10]
Okay, so I'll start off by saying that I don't have much time/brain capacity to do any complicated organising for this, however it would be nice to see it happen during the summer.

Last year there was Ruby in the Park a few times. I am basically thinking of doing this, but with learners groups. Everyone bring their own food, write down here what you want to bring, someone supplies the grill, we decided on a location and a time and date, and whoever can come SUPER!

I am thinking
Saturday 21st August, 2015
3pm
Gleisdreieck Park

Okay, go!

**Comment by berlintam** [comment]
that is a Friday :laughing: 
Do you mean the 22nd?

**Comment by sareg0** [comment]
Saturday 22nd :)

**Comment by PragTob** [comment]
I maybe can't make the 22nd, a friend has a birthday party there but I don't know what time so we'll see.

Otherwise great idea, although I'm more pro on tempelhofer feld/viktoria park (closer to home) - dunnno for tha latter if a bbq is legal there :)

**Comment by sareg0** [comment]
i quite like the idea of tempelhofer feld also.

On Sat, Aug 8, 2015 at 5:21 PM, Tobias Pfeiffer notifications@github.com
wrote:

> I maybe can't make the 22nd, a friend has a birthday party there but I
> don't know what time so we'll see.
> 
> Otherwise great idea, although I'm more pro on tempelhofer feld/viktoria
> park (closer to home) - dunnno for tha latter if a bbq is legal there :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rubycorns/organization/issues/10#issuecomment-128989631
> .

## 

Kindest Regards,
Sara and the Rails Girls Summer of Code Team
@RailsGirlsSoC https://twitter.com/RailsGirlsSoC

Kindest Regards,
Sara
@sareg0 https://twitter.com/sareg0
+49(0)17699393251

**Comment by berlintam** [comment]
oh. This is today. :frowning:

**Comment by sareg0** [comment]
Yeah, I haven't had time to get any further with it so I say we close and
do it some other time

On Saturday, 22 August 2015, Tam notifications@github.com wrote:

> oh. This is today. [image: :frowning:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rubycorns/organization/issues/10#issuecomment-133734390
> .

## 

Kindest Regards,
Sara and the Rails Girls Summer of Code Team
@RailsGirlsSoC https://twitter.com/RailsGirlsSoC

Kindest Regards,
Sara
@sareg0 https://twitter.com/sareg0
+49(0)17699393251
