### ISSUE TITLE
eurucamp outfits and swag

### ISSUE THREAD

**Issue by lislis** [rubycorns/organization#2]
So corns, as extensively discussed on the mailinglist we will rule eurucamp.
Planned are unicorn onesies and rubycorns tattoos.

The onesies come in blue, pink and purple, see here http://kigurumi-shop.com/Blue-Unicorn-Kigurumi.aspx
I volunteer to order for everyone and search for a store that does not ship from the US because that takes forever! The onesies come in one size, so just tell me the color that you want and I order. Deadline for the onesies is **Friday, June 19th**

I will order 200 tattoos from tattyoo.com. The order takes about 2 to 3 weeks so this will happen asap. I'll prepare the pdf for printing and paste some images for your viewing pleasure in here once I come around to do it.
# rubycornsrule

**Comment by sareg0** [comment]
#rubycornsrule
#sweeeeet!
I'm gonna take a purple :)

**Comment by berlintam** [comment]
I think I would also like purple pls!

btw, I saw a guy walking down the street today in a KANGAROO ONESIE. He looked pretty awesome.

**Comment by berlintam** [comment]
they are cheaper on the amazon: http://www.amazon.de/gp/product/B00FDIQX8C

**Comment by berlintam** [comment]
@lislis u need any help w/ anything? just let me know!

**Comment by lislis** [comment]
sry for the long silence! I thought about 'just' having the ascii corn as a sticker or maybe a typographic thing. My skills are limited but something like this 
![whatiseven](https://cloud.githubusercontent.com/assets/1006478/8145646/55e653c6-1210-11e5-8cf2-5d57a45050f5.png)

wdyt?

**Comment by berlintam** [comment]
I think this is great, as it generates discussion! ppl will read it, and then ask what a rubycorn is, and then we get to tell them about our group! genius! My only comment is that Rubycorn should be rubycorn (lowercase r). 

Would this be a sticker then or a tattoo? which is which now?

**Comment by lislis** [comment]
Cool, I'll make a lower case one. I was still thinking of tattoos and some information on the back. If we agree on the front I'll make the back in a similar style with our contact info and stuff

**Comment by til** [comment]
Very nice! Looking forward to proudly wear the tattoo at eurucamp!

**Comment by berlintam** [comment]
whilst in your unicorn onsie, @til ? :smile:

**Comment by til** [comment]
But then it wouldn't be visible! And I'd rather not put the tattoo on my
forehead ...

**Comment by lislis** [comment]
update: 
![whatiseven2](https://cloud.githubusercontent.com/assets/1006478/8150082/d9bd2cda-12db-11e5-85f8-1b8dc2966fc1.png)

**Comment by berlintam** [comment]
:+1:  !

**Comment by lislis** [comment]
first draft of the back:

![tattoo-back-v1](https://cloud.githubusercontent.com/assets/1006478/8170250/9a1c456e-13af-11e5-8d83-e3601a10173d.png)

**Comment by berlintam** [comment]
love it!
do we have https yet?

**Comment by lislis** [comment]
no, not yet. I could just leave out the protocol, like `//rubycorns.club` wdyt?

**Comment by berlintam** [comment]
i think that looks weird (like it's commented out or something). I say just leave the `http://` in.

**Comment by lislis** [comment]
mkay. once let's encrypt starts we can get that and just force https anyway

**Comment by sareg0** [comment]
I LOVE ALL THESE THINGS!

**Comment by berlintam** [comment]
oh dear... we can't back out now...
![screen shot 2015-06-17 at 11 26 09](https://cloud.githubusercontent.com/assets/4237285/8203653/c50aaf60-14e3-11e5-8b8f-39bcb5e5dd1c.png)

**Comment by FrauBienenstich** [comment]
hahaha...WHO'S THE MOLE???

**Comment by lislis** [comment]
Well, I guess that was me. I didn't think Sven would tweet it immediately... I blame social media!

**Comment by berlintam** [comment]
#whoislisapassing

**Comment by sareg0** [comment]
I think it's safe to assume that both Lisa and I let slip in the kitchen of Travis our secret planz

**Comment by PragTob** [comment]
So tam told me at least one coach has got to get one, so I'm gonna take one for the team and get one... ;)

I'd like an XL plz. "If you're in between 6 feet and 6 feet 2 inches, either size will fit, but the XL size might be a slightly better choice."

Color wise I found no option - but I'm often not the birghtest lookout :)

**Comment by berlintam** [comment]
@PragTob  WooOOOOOOoooooOOOOOOOh!!!

btw: http://www.buzzfeed.com/elainawahl/unicorn

**Comment by lislis** [comment]
Ok, I'll order the onsies tomorrow. Since myself, @berlintam and @sareg0 take purple, @PragTob you'll get purple as well. I email you further info directly. Guess what, We're all using email encryption ;)

**Comment by lislis** [comment]
Onesies and tattoos are on the way!
This will be so amazing!
Closing this now :)
