### ISSUE TITLE
3d Printer workshop

### ISSUE THREAD

**Issue by berlintam** [rubycorns/organization#3]
https://fablab.berlin/en/workshops/23-3d-printing-introduction.html

If we book in July, it's only 15 euro. 

It's on Wednesdays. 

Suggested Dates:
July: 15
August: 12, 19, 26

Who's in and when?

**Comment by sareg0** [comment]
I am in for 12 or 19 August

**Comment by lislis** [comment]
Hey, I'd be in. But only August 12th

**Comment by berlintam** [comment]
@BriocheBerlin what about the 12th?

**Comment by BriocheBerlin** [comment]
Upps, yes, 12th should work! Let's book :D

**Comment by lislis** [comment]
Sooooo, is  this happening? Does someone want to take the organization role?

**Comment by berlintam** [comment]
lets do it tonite

**Comment by sareg0** [comment]
when, where? how?

**Comment by lislis** [comment]
4 tickets: ORDERED!
Be there or be square!

**Comment by berlintam** [comment]
SUCH EXCITE!
