### ISSUE TITLE
euroku?

### ISSUE THREAD

**Issue by berlintam** [rubycorns/organization#5]
Anyone going to euroku?
http://www.euruko2015.org/

rubycorn field trip?

**Comment by sareg0** [comment]
I ammmm!!!!

**Comment by berlintam** [comment]
omggggggg.
what are your übernachtung plans?

**Comment by sareg0** [comment]
hehehe, none yet :) Open to suggesions. Should we all try to book together?

**Comment by berlintam** [comment]
that would be fun! oder!?

**Comment by sareg0** [comment]
okay I am booking a 6-person dorm with free cancellation

**Comment by berlintam** [comment]
haha wow, so fleissig! where is it/how much is it/for what dates?

**Comment by sareg0** [comment]
21EUR per night p/person, [Mieninger Hotel](http://www.booking.com/searchresults.en-gb.html?src=index&nflt=&ss_raw=Salz&error_url=http%3A%2F%2Fwww.booking.com%2Findex.en-gb.html%3Fsid%3D62504c88e89b2a84137fd695e766c62f%3Bdcid%3D1%3Bbb_ltbi%3D0%26%3B&dcid=1&lang=en-gb&sid=62504c88e89b2a84137fd695e766c62f&si=ai%2Cco%2Cci%2Cre%2Cdi&ss=Salzburg%2C+Salzburg%2C+Austria&checkin_monthday=16&checkin_year_month=2015-10&checkout_monthday=19&checkout_year_month=2015-10&no_rooms=1&group_adults=6&group_children=0&dest_type=city&dest_id=-1989985&ac_pageview_id=42515ed7c9e50092&ac_position=0&ac_langcode=en&ac_suggestion_list_length=5&place_types=#hotel_281558-back)

381EUR for 3 nights.

**Comment by sareg0** [comment]
Okay done. 

Meininger Hotel
Fürbergstraße 18-20
Schallmoos
5020 Salzburg
Österreich
http://www.meininger-hotels.com/de/hotels/salzburg/

25minute walk/15 minute public transport to venue

Free cancellation up until 15th Oktober

Total cost 381EUR for 6 person dorm
127EUR p/night
21EUR p/person (if 6 people share the cost)

If we find a better one, just say, we can cancel and book a different one

**Comment by sareg0** [comment]
Who wants to be in on the dorm.

**Comment by berlintam** [comment]
wow thanks! I'm in! how many nites did u book?

**Comment by lislis** [comment]
MEEEE OMG

**Comment by berlintam** [comment]
i'm blind, i guess fri, sat, sun

**Comment by lislis** [comment]
I'll be roadtrippin to Salzburg w/ Anika and probably @sareg0 but on the way back the car is still empty ;)

**Comment by berlintam** [comment]
WHEN ARE YOU COMING BACK?

**Comment by lislis** [comment]
@berlintam I thought of driving down on Friday and driving back on Monday

**Comment by lislis** [comment]
I'm talking about roadtripping to Salzburg for Euruku if that wasn't clear

**Comment by berlintam** [comment]
haha yes, i picked up on that :) that sounds AWESOME. let's discuss further at da cornz.

**Comment by sareg0** [comment]
okay, 3 spots taken for the hostel. Yep 3 nights; Friday, Saturday and Sunday night in the Hostel

**Comment by sareg0** [comment]
@Malwine @eljojo @berlintam @lislis @sareg0 and @katrin-k are the people taking the hostel

**Comment by lucaspinto** [comment]
I am too

**Comment by eljojo** [comment]
yeay!

**Comment by sareg0** [comment]
where are you all staying?

On Wed, Aug 5, 2015 at 12:38 AM, José Tomás Albornoz <
notifications@github.com> wrote:

> yeay!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rubycorns/organization/issues/5#issuecomment-127781396
> .

## 

Kindest Regards,
Sara and the Rails Girls Summer of Code Team
@RailsGirlsSoC https://twitter.com/RailsGirlsSoC

Kindest Regards,
Sara
@sareg0 https://twitter.com/sareg0
+49(0)17699393251

**Comment by lucaspinto** [comment]
@sareg0 @fannivuniconnu knows this

**Comment by fannivuniconnu** [comment]
We have booked the Hotel Krone 1512 (close to the venue)

**Comment by katrin-k** [comment]
@sareg0 awesome. thanks so much!

**Comment by sareg0** [comment]
such berlin contingent

**Comment by lucaspinto** [comment]
"On est chez nous" ("We're home")
https://www.youtube.com/watch?v=SXJ8llntHOo
