### ISSUE TITLE
EuruCamp

### ISSUE THREAD

**Issue by sareg0** [rubycorns/organization#6]
Hey good corns,

I have a spare ticket to Eurucamp now. I would like to give it to someone from a learning group and/or someone who really needs it and would otherwise not be able to attend. Could you help me out finding said person? Rubycorns get first preference, however.

**Comment by berlintam** [comment]
did you tweet?

**Comment by sareg0** [comment]
I have not, but I think I have found someone

**Comment by sareg0** [comment]
yipee!! I'll close this issue now

**Comment by PragTob** [comment]
IT'S **eurucamp** !!! !!!! :D :)
